/* chckid.f -- translated by f2c (version 19991025).
   You must link the resulting object file with the libraries:
	-lf2c -lm   (in that order)
*/

#include "f2c.h"
#include "__cspice_state.h"


typedef int chckid_state_t;
static chckid_state_t* get_chckid_state(cspice_t* state) {
	return 0;
}

/* $Procedure      CHCKID ( Check ID string ) */
/* Subroutine */ int chckid_(cspice_t* __global_state, char *class__, integer 
	*maxlen, char *id, ftnlen class_len, ftnlen id_len)
{
    /* Builtin functions */
    integer s_cmp(f2c_state_t*, char *, char *, ftnlen, ftnlen);

    /* Local variables */
    integer i__;
    integer l;
    extern /* Subroutine */ int chkin_(cspice_t*, char *, ftnlen);
    extern /* Subroutine */ int errch_(cspice_t*, char *, char *, ftnlen, 
	    ftnlen);
    integer chrcod;
    extern integer lastnb_(cspice_t*, char *, ftnlen);
    extern /* Subroutine */ int sigerr_(cspice_t*, char *, ftnlen);
    extern /* Subroutine */ int chkout_(cspice_t*, char *, ftnlen);
    extern /* Subroutine */ int setmsg_(cspice_t*, char *, ftnlen);
    extern /* Subroutine */ int errint_(cspice_t*, char *, integer *, ftnlen);
    extern integer frstnp_(cspice_t*, char *, ftnlen);
    extern logical return_(cspice_t*);


    /* Module state */
    chckid_state_t* __state = get_chckid_state(__global_state);
/* $ Abstract */

/*     Validate an ID string:  check for non-printing characters */
/*     or excessive non-blank length. */

/* $ Disclaimer */

/*     THIS SOFTWARE AND ANY RELATED MATERIALS WERE CREATED BY THE */
/*     CALIFORNIA INSTITUTE OF TECHNOLOGY (CALTECH) UNDER A U.S. */
/*     GOVERNMENT CONTRACT WITH THE NATIONAL AERONAUTICS AND SPACE */
/*     ADMINISTRATION (NASA). THE SOFTWARE IS TECHNOLOGY AND SOFTWARE */
/*     PUBLICLY AVAILABLE UNDER U.S. EXPORT LAWS AND IS PROVIDED "AS-IS" */
/*     TO THE RECIPIENT WITHOUT WARRANTY OF ANY KIND, INCLUDING ANY */
/*     WARRANTIES OF PERFORMANCE OR MERCHANTABILITY OR FITNESS FOR A */
/*     PARTICULAR USE OR PURPOSE (AS SET FORTH IN UNITED STATES UCC */
/*     SECTIONS 2312-2313) OR FOR ANY PURPOSE WHATSOEVER, FOR THE */
/*     SOFTWARE AND RELATED MATERIALS, HOWEVER USED. */

/*     IN NO EVENT SHALL CALTECH, ITS JET PROPULSION LABORATORY, OR NASA */
/*     BE LIABLE FOR ANY DAMAGES AND/OR COSTS, INCLUDING, BUT NOT */
/*     LIMITED TO, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, */
/*     INCLUDING ECONOMIC DAMAGE OR INJURY TO PROPERTY AND LOST PROFITS, */
/*     REGARDLESS OF WHETHER CALTECH, JPL, OR NASA BE ADVISED, HAVE */
/*     REASON TO KNOW, OR, IN FACT, SHALL KNOW OF THE POSSIBILITY. */

/*     RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF */
/*     THE SOFTWARE AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY */
/*     CALTECH AND NASA FOR ALL THIRD-PARTY CLAIMS RESULTING FROM THE */
/*     ACTIONS OF RECIPIENT IN THE USE OF THE SOFTWARE. */

/* $ Required_Reading */

/*     None. */

/* $ Keywords */

/*     STRING */
/*     UTILITY */

/* $ Declarations */
/* $ Brief_I/O */

/*     Variable  I/O  Description */
/*     --------  ---  -------------------------------------------------- */
/*     CLASS      I   A description of the class to which ID belongs. */
/*     MAXLEN     I   Maximum allowed non-blank length of ID. */
/*     ID         I   The ID string to be validated. */

/* $ Detailed_Input */

/*     CLASS          is a descriptive string indicating the type of */
/*                    object represented by ID.  Examples are */
/*                    'SPK segment identifier', 'DAF internal file name', */
/*                    or 'EK table name'. */

/*                    If the input ID is found to be invalid, CLASS is */
/*                    used in the error message generated by this */
/*                    routine. */

/*     MAXLEN         is the maximum allowed non-blank length of the */
/*                    input ID string.  If ID has any non-blank */
/*                    characters at positions greater than MAXLEN, */
/*                    an error will be signalled. */

/*     ID             is the input ID string to be checked.  In order */
/*                    to be considered valid, ID must contain only */
/*                    printing characters and must satisfy the condition */

/*                       LASTNB( ID )  <  MAXLEN */
/*                                     - */

/* $ Detailed_Output */

/*     None.  See $Particulars for a description of the effect of this */
/*     routine. */

/* $ Parameters */

/*     None. */

/* $ Exceptions */

/*     1)  If ID contains any nonprintable characters, the error */
/*         SPICE(NONPRINTABLECHARS) is signalled. */

/*     2)  If MAXLEN is non-positive, the error SPICE(INVALIDCOUNT) is */
/*          signalled. */

/*     3)  If ID contains any non-blank characters past position */
/*         MAXLEN, the error SPICE(IDSTRINGTOOLONG) is signalled. */

/*     4)  If CLASS contains any non-printing characters, the error */
/*         SPICE(NONPRINTABLECHARS) is signalled. */

/*     5)  CLASS is allowed to be blank.  The word 'ID' is used in */
/*         place of the class string in any error messages in this */
/*         case. */

/*     6)  Error messages signalled by this routine have a maximum */
/*         length of 320 characters.  If substitution of CLASS and */
/*         ID into the long messages causes overflow, the messages */
/*         will be truncated on the right. */

/* $ Files */

/*     None. */

/* $ Particulars */

/*     This routine operates by side effects:  it validates an ID string */
/*     and signals an error if the ID has either of the following */
/*     problems: */

/*        - There are non-printing characters in the ID string. */

/*        - The last non-blank character in the string occurs at a */
/*          location having index higher than a specified value. */

/*     The error message signalled by this routine contains the offending */
/*     ID string and indicates the class of item to which ID belongs. */
/*     The form of the message is: */

/*         The <CLASS> <'ID'> is invalid; <reason> */

/* $ Examples */

/*     1)  If */

/*            CLASS  = 'segment identifier' */
/*            MAXLEN =  40 */

/*         and */

/*            ID = 'Example EK created on March 28, 1995 by NJB/NAIF' */

/*         the error message */

/*            The segment identifier 'Example EK created on March 28, */
/*            1995 by NJB/NAIF' is invalid; the last non-blank character */
/*            is located at position 48. */

/*         will be signalled. */

/* $ Restrictions */

/*     None. */

/* $ Literature_References */

/*     None. */

/* $ Author_and_Institution */

/*     N.J. Bachman   (JPL) */

/* $ Version */

/* -    SPICELIB Version 1.0.0, 16-JUN-1995 (NJB) */

/* -& */
/* $ Index_Entries */

/*     check an ID string */
/*     validate an ID string */

/* -& */

/*     SPICELIB functions */


/*     Local variables */


/*     Standard SPICE error handling. */

    if (return_(__global_state)) {
	return 0;
    } else {
	chkin_(__global_state, "CHCKID", (ftnlen)6);
    }

/*     Check CLASS before trying to use it in an error message. */

    i__ = frstnp_(__global_state, class__, class_len);
    if (i__ > 0) {
	chrcod = *(unsigned char *)&class__[i__ - 1];
	setmsg_(__global_state, "The class string '#' is invalid; this strin"
		"g contains a non-printing character (ICHAR = #) at position "
		"#.", (ftnlen)105);
	errch_(__global_state, "#", class__, (ftnlen)1, class_len);
	errint_(__global_state, "#", &chrcod, (ftnlen)1);
	errint_(__global_state, "#", &i__, (ftnlen)1);
	sigerr_(__global_state, "SPICE(NONPRINTABLECHARS)", (ftnlen)24);
	chkout_(__global_state, "CHCKID", (ftnlen)6);
	return 0;
    }

/*     MAXLEN must be a sensible value. */

    if (*maxlen < 1) {
	setmsg_(__global_state, "Non-blank length limit MAXLEN should be pos"
		"itive but was #.", (ftnlen)59);
	errint_(__global_state, "#", maxlen, (ftnlen)1);
	sigerr_(__global_state, "SPICE(INVALIDCOUNT)", (ftnlen)19);
	chkout_(__global_state, "CHCKID", (ftnlen)6);
	return 0;
    }
    l = lastnb_(__global_state, id, id_len);

/*     The ID must not be too long. */

    if (l > *maxlen) {
	setmsg_(__global_state, "The # '#' is invalid; the last non-blank ch"
		"aracter is located at position #; the maximum allowed length"
		" is #.", (ftnlen)109);
	if (s_cmp(&__global_state->f2c, class__, " ", class_len, (ftnlen)1) !=
		 0) {
	    errch_(__global_state, "#", class__, (ftnlen)1, class_len);
	} else {
	    errch_(__global_state, "#", "ID", (ftnlen)1, (ftnlen)2);
	}
	errch_(__global_state, "#", id, (ftnlen)1, id_len);
	errint_(__global_state, "#", &l, (ftnlen)1);
	errint_(__global_state, "#", maxlen, (ftnlen)1);
	sigerr_(__global_state, "SPICE(IDSTRINGTOOLONG)", (ftnlen)22);
	chkout_(__global_state, "CHCKID", (ftnlen)6);
	return 0;
    }

/*     Look for non-printing characters in ID. */

    i__ = frstnp_(__global_state, id, id_len);
    if (i__ > 0) {
	chrcod = *(unsigned char *)&id[i__ - 1];
	setmsg_(__global_state, "The # '#' is invalid; this string contains "
		"a non-printing character (ICHAR = #) at position #.", (ftnlen)
		94);
	if (s_cmp(&__global_state->f2c, class__, " ", class_len, (ftnlen)1) !=
		 0) {
	    errch_(__global_state, "#", class__, (ftnlen)1, class_len);
	} else {
	    errch_(__global_state, "#", "ID", (ftnlen)1, (ftnlen)2);
	}
	errch_(__global_state, "#", id, (ftnlen)1, id_len);
	errint_(__global_state, "#", &chrcod, (ftnlen)1);
	errint_(__global_state, "#", &i__, (ftnlen)1);
	sigerr_(__global_state, "SPICE(NONPRINTABLECHARS)", (ftnlen)24);
	chkout_(__global_state, "CHCKID", (ftnlen)6);
	return 0;
    }
    chkout_(__global_state, "CHCKID", (ftnlen)6);
    return 0;
} /* chckid_ */

